from termcolor import colored, cprint
def print_sword():
    cprint("                                                                                          ://", 'blue')
    cprint("                                                                                 .-://+//:/", 'blue')
    cprint("                                                                             ..-::/:----::-./", 'blue')
    cprint("                                                                          -/--..-------:/-..:-", 'blue')
    cprint("                                                                        `+/....------:/:....s`", 'blue')
    cprint("                                                                      :+-....-----:/:......h", 'blue')
    cprint("                                                                    -+:....------//-......-y", 'blue')
    cprint("                                                                   `//-..-------//-........o+", 'blue')
    cprint("                                                                 :+-..-------/+:..........h:", 'blue')
    cprint("                                                               -+:...------:+:-..........:/", 'blue')
    cprint("                                                             `//-..------:+/-..........:-`", 'blue')
    cprint("                                                           :+:..------:++-..........:-`", 'blue')
    cprint("                                                         .+/..------:/+:..........::`", 'blue')
    cprint("                                                        `/+-.-------/o/-.........::`", 'blue')
    cprint("                                                       :o:-------:/o/---.......::.", 'blue')
    cprint("                                                     .+/-------::++:--.......::.", 'blue')
    cprint("                                                   `/+-------::+o:---......:/.", 'blue')
    cprint("                                                  :o:------::+o/----.....:/.", 'blue')
    cprint("                                                .o/------::/s+-----....:/-", 'blue')
    cprint("                                              `/o------::/so------...:/-", 'blue')
    cprint("                                             -o:-----:::ss:------.-:+-", 'blue')
    cprint("                                           .o+-----:::os/--------:+-", 'blue')
    cprint("                                          /o-----:::+y+--------:+:", 'blue')
    cprint("                                        -s:----:::+yo:-------:+:", 'blue')
    cprint("                                        `o+----:::/ys::------:+:", 'blue')
    cprint("                                     +s----::::yy:::-----:o/", 'blue')
    cprint("                                   -s/---::::sy/:::----:o/", 'blue')
    cprint("                                 `o+---::::oh+::::---:o/`", 'blue')
    cprint("                   :/-          +s:--::::+ho:::::--:o/`", 'blue')
    cprint("                 .+-.-/:`     :s/--::::+hs/:::::-:o+`", 'blue')
    cprint("               `/:.....-::. .o+:-::::/yy/:::::::o+`", 'blue')
    cprint("               oo/......--:/y/-::::/sh+:::::::o+.", 'blue')
    cprint("                `-++/:------:/++::sho/::::::o+.", 'blue')
    cprint("                    `-//+::::::/+yy/::::::o+.", 'blue')
    cprint("                      +hmmhs+/::://++/::oo.", 'blue')
    cprint("                    .+mmNNNNmmy/:::::/+y-", 'blue')
    cprint("                   sdNNmmmmmmmNms:-----:/-.", 'blue')
    cprint("                `:ommmmNNNNNNmmmmd+:-----://-`", 'blue')
    cprint("     `         `sNNNNNmmmmmmmmNNmd-//-......:o.", 'blue')
    cprint("    ///.     .yhmmmmmmmNNNNNmmmo-`  ./:....-:.", 'blue')
    cprint(" `+:`.:+:``-smmNNNNNNmmmmmmmho       -/--/.", 'blue')
    cprint(" `s-.....:+hNNNNmmmmmmmNNNmm:          `:-", 'blue')
    cprint(" `:+/------:odmmmNNNNNmmms:-", 'blue')
    cprint("    ./o:-----:+ymmmmmmmhs", 'blue')
    cprint("    `s-/+/:::::::odmNm:", 'blue')
    cprint("    .s+-.:///:::---/so`", 'blue')
    cprint("      .+o:.-://:---...::.", 'blue')
    cprint("         :+/-.-/+:-...``-/", 'blue')
    cprint("           `/++:..:/..::-", 'blue')
    cprint("                             -/.", 'blue')
